spring:
  application:
    name: keycloak-auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
          jwk-set-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}/protocol/openid-connect/certs
server:
  port: 6700

app:
  keycloak:
    admin:
      clientId: PH
      clientSecret: rTuXY9QyjACS2heH2OGgy19tKEZrzlJw
      adminClientId: admin-cli
      adminClientSecret: 5NZHfNmz78pV6WcKuJUjDDlzsJILEBef
    realm: PsikoHekim
    serverUrl: http://localhost:8080