spring:
  application:
    name: keycloak-auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
          jwk-set-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}/protocol/openid-connect/certs
server:
  port: 6700

app:
  keycloak:
    admin:
      clientId: PH
      clientSecret: wCDgOs6Vh7qlrIDRXEfPch1SXdVccJQb
      adminClientId: admin-cli
      adminClientSecret: 6LnAoUMLSbQS2OJ8uwxjR6hB0FhFAcWJ
    realm: PsikoHekim
    serverUrl: http://localhost:9082